package com.hrpd.codereview.model;

/**
 * Represents a single code review finding identified by an AI-powered reviewer.
 * 
 * <p>A finding captures a specific issue or concern discovered during code review,
 * including its location, description, and recommended remediation. Each finding
 * is associated with a particular reviewer type (security, performance, clean code)
 * and assigned a severity level to indicate its importance.</p>
 * 
 * <p>This record is immutable and represents the core data structure for all
 * review findings generated by the parallel code review system.</p>
 * 
 * @param filePath the relative path to the file where the issue was found
 * @param lineStart the starting line number of the code section (1-based)
 * @param lineEnd the ending line number of the code section (1-based)
 * @param title a brief, descriptive title for the finding
 * @param rationale detailed explanation of why this is considered an issue
 * @param suggestion specific recommendation for how to fix or improve the code
 * @param severity the importance level of this finding (BLOCKER, HIGH, MEDIUM, LOW, INFO)
 * @param reviewer the type of reviewer that identified this finding
 * 
 * @see Severity
 * @see ReviewerType
 */
public record Finding(
        String filePath,
        int lineStart,
        int lineEnd,
        String title,
        String rationale,
        String suggestion,
        Severity severity,
        ReviewerType reviewer
) {}
